[Bug 13744] - [Gamma - Flx Model APIs](Regression) - TypeError: 'NoneType' object has no attribute '__getitem__'  - Checking expected condition for None to avoid exception